[features]
seeds = false
[programs.localnet]
upgrad00r = "84zHEoSwTo6pb259RtmeYQ5KNStik8pib815q7reZjdx"

[programs.devnet]
upgrad00r = "84zHEoSwTo6pb259RtmeYQ5KNStik8pib815q7reZjdx"
[programs.mainnet]
upgrad00r = "84zHEoSwTo6pb259RtmeYQ5KNStik8pib815q7reZjdx"
[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/jarettdunn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
