[features]
seeds = false
[programs.localnet]
FUS00r = "GR8qnkCuwBM3aLkAdMQyy3n6NacecPha7xhwkmLEVNBM"

[programs.devnet]
FUS00r = "GR8qnkCuwBM3aLkAdMQyy3n6NacecPha7xhwkmLEVNBM"
[programs.mainnet]
FUS00r = "GR8qnkCuwBM3aLkAdMQyy3n6NacecPha7xhwkmLEVNBM"
[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/jarettdunn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
